### ISSUE TITLE
Need to implement only for S3

### ISSUE THREAD

**Issue by DivagarSivasamy** [omrikiei/aws_logging_handlers#21]
```
import logging
from aws_logging_handlers.S3 import S3Handler
import boto3
s3 = boto3.client("s3")
bucket="sing-dev-chumbucket1" # The bucket should already exist

s3_handler = S3Handler("error/output/", bucket, workers=3)

formatter = logging.Formatter('[%(asctime)s] %(filename)s:%(lineno)d} %(levelname)s - %(message)s')
s3_handler.setFormatter(formatter)
logger = logging.getLogger('root')
logger.setLevel(logging.INFO)
logger.addHandler(s3_handler)
for i in range(0, 100):
    logger.info("test info message")
    logger.warning("test warning message")
    logger.error("test error message")

logging.shutdown()

getting an error 
File "C:/Users/Administrator/PycharmProjects/baselineloader/venv/Scripts/testarg.py", line 7, in <module>
    s3_handler = S3Handler("error/output/", bucket, workers=3)
  File "C:\Users\Administrator\PycharmProjects\baselineloader\venv\lib\site-packages\aws_logging_handlers\S3\__init__.py", line 329, in __init__
    self.stream = S3Stream(self.bucket, key, chunk_size=chunk_size, max_file_log_time=time_rotation,
TypeError: ABCMeta object got multiple values for keyword argument 'workers'

kindly help me .
```

**Comment by Nirmal1212** [comment]
I am also facing the same issue. 
`Traceback (most recent call last):
  File "logging_test.py", line 8, in <module>
    s3_handler = S3Handler(log_path, bucket, workers=3)
  File "/usr/local/lib/python3.6/site-packages/aws_logging_handlers/S3/__init__.py", line 331, in __init__
    compress=compress, **boto_session_kwargs)
TypeError: ABCMeta object got multiple values for keyword argument 'workers'
`

**Comment by newbery** [comment]
The documentation is incorrect for the S3 example. Use "max_threads=3" instead. The code should probably be updated to match the Kinesis api.
